# docker compose up -d --build
# docker compose kill

version: "3"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-1
      - app-2
    container_name: nginx-container

  app-1:
    image: nginx
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - ./app-1/default.conf:/etc/nginx/conf.d/default.conf
      - ./app-1/dist:/projects
    container_name: app-1-container

  app-2:
    image: nginx
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - ./app-2/default.conf:/etc/nginx/conf.d/default.conf
      - ./app-2/dist:/projects
    container_name: app-2-container

  node-api:
    # image: NODEJS latest
    image: node:latest
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    volumes:
      - ./Smart-Api/:/projects
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    command: ["node", "/projects/bin/www"]
    working_dir: /projects
    container_name: nodeapi-Smart-Api
