# docker compose up -d --build
# docker compose kill

version: "3"

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-container

  app-1:
    image: nginx
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - ./app-1/default.conf:/etc/nginx/conf.d/default.conf
      - ./app-1/dist:/projects
    container_name: app-1-container
  # smart-factory-dashboard
  app-2:
    image: nginx
    restart: unless-stopped
    # ports:
    #   - "8081:80"
    volumes:
      - ./app2-build/default.conf:/etc/nginx/conf.d/default.conf
      - ./app2-build/dist:/projects
    container_name: app-2-container
